version: '3.5'

volumes:
  mysql-volume:

services:
  mysql:
    restart: unless-stopped
    build:
      context: mysql/
      args: 
        SQL_VERSION: ${SQL_VERSION}
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - 3306:3306
    volumes: 
      - mysql-volume:/var/lib/mysql
      - ./init.sql:/data/application/init.sql
    networks:
      - serv
  phpmyadmin:
    restart: unless-stopped
    build:
      context: phpmyadmin/
    container_name: phpmyadmin
    links:
      - "mysql:db"
    ports:
      - 8081:80
    networks:
      - serv

networks:
  serv:
    driver: bridge